### ISSUE TITLE
PythiaConverter_ee_Z_bbbar Test fails

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4SimDelphes#65] opened 2021-10-20 15:09 UTC
https://github.com/vvolkl/k4SimDelphes/runs/3953159143?check_suite_focus=true#step:9:2545
`MC relations of candidate 0 are different between delphes and edm4hep output`

Possibly due to updated dependencies and has to be updated itself.

**Comment by tmadlener** [comment] 2022-02-28 14:08
After some debugging this seems to be a problem in the comparison of the outputs, specifically there is a "mismatch" of the associated MC particles to the first `EFlowNeutralHadron` from delphes. However, this is a bit puzzling, as we seem to run into a root issue(?):

```bash
cd <build-dir>/tests
root pythia_converter_output_ee_Z_bbbar_delphes.root
```
Then having a look at the offending object in the delphes file via
```console
root [1] gSystem->Load("libDelphes")
(int) 0
root [2] auto* dt = (TTree*) _file0->Get("Delphes");
root [3] auto tr = std::make_unique<ExRootTreeReader>(dt);
root [4] auto* hadrons = tr->UseBranch("EFlowNeutralHadron");
root [5] auto* mcs = tr->UseBranch("Particle");
root [6] tr->ReadEntry(0)
root [7] auto* had = (Tower*) hadrons->At(0);
root [8] had->Particles
(TRefArray &) { @0x7ffd4c437ac0, @0x7ffd4c437a98, @0x7ffd4c437a98 }
root [9] had->Particles.GetEntries()
(int) 4
```
It is a bit puzzling why looking at the `TRefArray` via `had->Particles` seems to show an array with 3 entries, but querying for the size gives 4. I will try to see if I can reproduce this with a different root release.

**Comment by tmadlener** [comment] 2022-03-01 10:23
Looking further into this, it looks like during conversion we still have all entries accessible, and we do get 4 associated MC particles from delphes. However, in this case the 4 entries are only 2 particles where one appears three times. This seems to happen only for the `EFlowNeutralHadrons` but not for other `Tower` collections. I will contact the Delphes developers to see whether this is a problem on the Delphes side already.

**Comment by tmadlener** [comment] 2022-03-03 08:06
The underlying problem has been fixed in upstream Delphes with these commits:

https://github.com/delphes/delphes/commit/2a2f3109ca019be4871a612075c36e93710e124f
https://github.com/delphes/delphes/commit/4e8e72b29f2e9bc564ccf210abe4da8e61623055

Our nightly build has already picked these up and the tests are passing again now: https://github.com/key4hep/k4SimDelphes/runs/5403551196?check_suite_focus=true

**Closed by tmadlener** 2022-03-03 08:06 UTC
